using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SparklrSharp;
using SparklrSharp.Sparklr;
using System.Threading.Tasks;
using System.Linq;
using System.Data.Linq;
using System.Collections.Generic;

namespace SparklrTests
{
    [TestClass]
    public class TestConversations
    {
        /// <summary>
        /// Contains a user that has send a specified number of messages to the user used for unit-testing
        /// </summary>
        private const int TestMessagesFromId = 1864;

        /// <summary>
        /// The number of messages in the conversation.
        /// </summary>
        private const int TestMessageCount = 4;

        /// <summary>
        /// A recipient to send testmessages to
        /// </summary>
        private const int TestRecipient = 591;

        [TestMethod]
        [ExpectedException(typeof(SparklrSharp.Exceptions.NotAuthorizedException))]
        public async Task TestConversationsNotAuthorized()
        {
            Connection conn = await Credentials.CreateSession();
            await conn.RefreshInboxAsync();
            await conn.SignoffAsync();

            Conversation convo = conn.GetConversationWith(conn.Inbox[0].Author);
            await convo.LoadMore();
        }

        [TestMethod]
        public async Task TestConversationsLoadMessagesWithCompleteUser()
        {
            Connection conn = await Credentials.CreateSession();
            await conn.RefreshInboxAsync();

            User u = (from Message m in conn.Inbox where m.Author.UserId == TestMessagesFromId select m.Author).First();

            Conversation convo = conn.GetConversationWith(u);

            Assert.IsTrue(convo.NeedsRefresh);
            await convo.LoadMore();

            Assert.AreEqual(convo.Messages.Count, TestMessageCount);

            Assert.IsTrue(convo.NeedsRefresh);
            await convo.LoadMore();

            Assert.IsFalse(convo.NeedsRefresh);

            Assert.AreSame(convo.ConversationPartner, u);
        }

        [TestMethod]
        public async Task TestConversationsLoadMessagesWithUserid()
        {
            Connection conn = await Credentials.CreateSession();
            await conn.RefreshInboxAsync();

            User u = (from Message m in conn.Inbox where m.Author.UserId == TestMessagesFromId select m.Author).First();

            Conversation convo = await conn.GetConversationWithUserIdAsync(TestMessagesFromId);

            Assert.IsTrue(convo.NeedsRefresh);
            await convo.LoadMore();

            Assert.AreEqual(convo.Messages.Count, TestMessageCount);

            Assert.IsTrue(convo.NeedsRefresh);
            await convo.LoadMore();

            Assert.IsFalse(convo.NeedsRefresh);

            Assert.AreSame(convo.ConversationPartner, u);
        }

        [TestMethod]
        [ExpectedException(typeof(SparklrSharp.Exceptions.NoDataFoundException))]
        public async Task TestConversationsLoadMessagesWithInvalidUserid()
        {
            Connection conn = await Credentials.CreateSession();
            await conn.RefreshInboxAsync();

            User u = (from Message m in conn.Inbox where m.Author.UserId == TestMessagesFromId select m.Author).First();

            Conversation convo = await conn.GetConversationWithUserIdAsync(int.MaxValue);
        }

        [TestMethod]
        public async Task TestIEnumerableConversation()
        {
            Connection conn = await Credentials.CreateSession();
            await conn.RefreshInboxAsync();

            IEnumerable<Message> messages = conn.ConversationWith((from Message m in conn.Inbox where m.Author.UserId == TestMessagesFromId select m.Author).First());

            int number = 0;

            foreach (Message m in messages)
                number++;

            Assert.AreEqual(number, TestMessageCount);
        }

        [TestMethod]
        public async Task TestConversationsSendValidMessage()
        {
            Connection conn = await Credentials.CreateSession();
            await conn.RefreshInboxAsync();

            Conversation convo = await conn.GetConversationWithUserIdAsync(TestRecipient);

            while (convo.NeedsRefresh)
                await convo.LoadMore();

            int prevCount = convo.Messages.Count;

            Assert.IsFalse(convo.NeedsRefresh);

            bool success = await convo.SendMessage(String.Format("Test-Message generated by Unit-Test on {0}", DateTime.Now));

            Assert.IsTrue(success);
            Assert.IsTrue(convo.NeedsRefresh);

            while (convo.NeedsRefresh)
                await convo.LoadMore();

            int newCount = convo.Messages.Count;

            Assert.AreEqual(prevCount + 1, newCount, "New message not in refreshed messages");
        }

        [TestMethod]
        [ExpectedException(typeof(ArgumentException))]
        public async Task TestConversationsSendInvalidMessage()
        {
            Connection conn = await Credentials.CreateSession();
            await conn.RefreshInboxAsync();

            Conversation convo = await conn.GetConversationWithUserIdAsync(TestRecipient);

            string m = "-";

            for (int i = 0; i <= 520; i++)
                m = m + "-";

            while (convo.NeedsRefresh)
                await convo.LoadMore();

            int prevCount = convo.Messages.Count;

            Assert.IsFalse(convo.NeedsRefresh);

            bool success = await convo.SendMessage(m);

            Assert.IsFalse(convo.NeedsRefresh);
        }
    }
}
