//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18213
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Phone.Controls.Updated.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Phone.Controls.Updated.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid FilterMode enumeration value. The value must be one of the defined AutoCompleteFilterMode values to be accepted. ähnelt.
        /// </summary>
        internal static string AutoComplete_OnFilterModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnFilterModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero. ähnelt.
        /// </summary>
        internal static string AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid MinimumPopulateDelay value &apos;{0}&apos;. The value must be greater than or equal to zero. ähnelt.
        /// </summary>
        internal static string AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot set read-only property SearchText. ähnelt.
        /// </summary>
        internal static string AutoComplete_OnSearchTextPropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("AutoComplete_OnSearchTextPropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid type. Argument must be of the type System.DateTime. ähnelt.
        /// </summary>
        internal static string InvalidDateTimeArgument {
            get {
                return ResourceManager.GetString("InvalidDateTimeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid operation. The IsExpanded property cannot be modified when IsNonExpandable is set to true. ähnelt.
        /// </summary>
        internal static string InvalidExpanderViewOperation {
            get {
                return ResourceManager.GetString("InvalidExpanderViewOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid argument. The number of months should be greater than 1 and less than 12. ähnelt.
        /// </summary>
        internal static string InvalidNumberOfMonths {
            get {
                return ResourceManager.GetString("InvalidNumberOfMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid argument. The number of time units should be greater than 1. ähnelt.
        /// </summary>
        internal static string InvalidNumberOfTimeUnits {
            get {
                return ResourceManager.GetString("InvalidNumberOfTimeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SelectedIndex must always be set to a valid value. ähnelt.
        /// </summary>
        internal static string InvalidSelectedIndex {
            get {
                return ResourceManager.GetString("InvalidSelectedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SelectedItem must always be set to a valid value. ähnelt.
        /// </summary>
        internal static string InvalidSelectedItem {
            get {
                return ResourceManager.GetString("InvalidSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid argument. Future dates and times are not supported. ähnelt.
        /// </summary>
        internal static string NonSupportedDateTime {
            get {
                return ResourceManager.GetString("NonSupportedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The RoutedPropertyChangingEvent cannot be canceled! ähnelt.
        /// </summary>
        internal static string RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation {
            get {
                return ResourceManager.GetString("RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;. ähnelt.
        /// </summary>
        internal static string TypeConverters_Convert_CannotConvert {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; cannot convert from &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string TypeConverters_ConvertFrom_CannotConvertFromType {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type was unexpected. ähnelt.
        /// </summary>
        internal static string UnexpectedType {
            get {
                return ResourceManager.GetString("UnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid length value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string WrapPanel_OnItemHeightOrWidthPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("WrapPanel_OnItemHeightOrWidthPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Orientation value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string WrapPanel_OnOrientationPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("WrapPanel_OnOrientationPropertyChanged_InvalidValue", resourceCulture);
            }
        }
    }
}
