//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18213
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Phone.Controls.Updated.LocalizedResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Phone.Controls.Updated.LocalizedResources.ControlResources", typeof(ControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about a minute ago ähnelt.
        /// </summary>
        public static string AboutAMinuteAgo {
            get {
                return ResourceManager.GetString("AboutAMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about a month ago ähnelt.
        /// </summary>
        public static string AboutAMonthAgo {
            get {
                return ResourceManager.GetString("AboutAMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about an hour ago ähnelt.
        /// </summary>
        public static string AboutAnHourAgo {
            get {
                return ResourceManager.GetString("AboutAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about a week ago ähnelt.
        /// </summary>
        public static string AboutAWeekAgo {
            get {
                return ResourceManager.GetString("AboutAWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALARM REPEATS ON ähnelt.
        /// </summary>
        public static string AlarmRepeatsOn {
            get {
                return ResourceManager.GetString("AlarmRepeatsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bytes ähnelt.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CHOOSE DATE ähnelt.
        /// </summary>
        public static string DatePickerTitle {
            get {
                return ResourceManager.GetString("DatePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cancel ähnelt.
        /// </summary>
        public static string DateTimePickerCancelText {
            get {
                return ResourceManager.GetString("DateTimePickerCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die done ähnelt.
        /// </summary>
        public static string DateTimePickerDoneText {
            get {
                return ResourceManager.GetString("DateTimePickerDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GB ähnelt.
        /// </summary>
        public static string Gigabyte {
            get {
                return ResourceManager.GetString("Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KB ähnelt.
        /// </summary>
        public static string Kilobyte {
            get {
                return ResourceManager.GetString("Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last Friday ähnelt.
        /// </summary>
        public static string last_Friday {
            get {
                return ResourceManager.GetString("last Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last Monday ähnelt.
        /// </summary>
        public static string last_Monday {
            get {
                return ResourceManager.GetString("last Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last Saturday ähnelt.
        /// </summary>
        public static string last_Saturday {
            get {
                return ResourceManager.GetString("last Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last Sunday ähnelt.
        /// </summary>
        public static string last_Sunday {
            get {
                return ResourceManager.GetString("last Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last Thursday ähnelt.
        /// </summary>
        public static string last_Thursday {
            get {
                return ResourceManager.GetString("last Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last Tuesday ähnelt.
        /// </summary>
        public static string last_Tuesday {
            get {
                return ResourceManager.GetString("last Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last Wednesday ähnelt.
        /// </summary>
        public static string last_Wednesday {
            get {
                return ResourceManager.GetString("last Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MB ähnelt.
        /// </summary>
        public static string Megabyte {
            get {
                return ResourceManager.GetString("Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on Friday ähnelt.
        /// </summary>
        public static string on_Friday {
            get {
                return ResourceManager.GetString("on Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on Monday ähnelt.
        /// </summary>
        public static string on_Monday {
            get {
                return ResourceManager.GetString("on Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on Saturday ähnelt.
        /// </summary>
        public static string on_Saturday {
            get {
                return ResourceManager.GetString("on Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on Sunday ähnelt.
        /// </summary>
        public static string on_Sunday {
            get {
                return ResourceManager.GetString("on Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on Thursday ähnelt.
        /// </summary>
        public static string on_Thursday {
            get {
                return ResourceManager.GetString("on Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on Tuesday ähnelt.
        /// </summary>
        public static string on_Tuesday {
            get {
                return ResourceManager.GetString("on Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on Wednesday ähnelt.
        /// </summary>
        public static string on_Wednesday {
            get {
                return ResourceManager.GetString("on Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die over a year ago ähnelt.
        /// </summary>
        public static string OverAYearAgo {
            get {
                return ResourceManager.GetString("OverAYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} ähnelt.
        /// </summary>
        public static string PartOfWhole {
            get {
                return ResourceManager.GetString("PartOfWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pause ähnelt.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die every day ähnelt.
        /// </summary>
        public static string RepeatsEveryDay {
            get {
                return ResourceManager.GetString("RepeatsEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die only once ähnelt.
        /// </summary>
        public static string RepeatsOnlyOnce {
            get {
                return ResourceManager.GetString("RepeatsOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weekdays ähnelt.
        /// </summary>
        public static string RepeatsOnWeekdays {
            get {
                return ResourceManager.GetString("RepeatsOnWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weekends ähnelt.
        /// </summary>
        public static string RepeatsOnWeekends {
            get {
                return ResourceManager.GetString("RepeatsOnWeekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die resume ähnelt.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Canceled ähnelt.
        /// </summary>
        public static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die complete ähnelt.
        /// </summary>
        public static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading... ähnelt.
        /// </summary>
        public static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die paused ähnelt.
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pending ähnelt.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unknown ähnelt.
        /// </summary>
        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading... ähnelt.
        /// </summary>
        public static string StatusUploading {
            get {
                return ResourceManager.GetString("StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting... ähnelt.
        /// </summary>
        public static string StatusWaiting {
            get {
                return ResourceManager.GetString("StatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting... ähnelt.
        /// </summary>
        public static string StatusWaitingForExternalPower {
            get {
                return ResourceManager.GetString("StatusWaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Low battery ähnelt.
        /// </summary>
        public static string StatusWaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("StatusWaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for connection ähnelt.
        /// </summary>
        public static string StatusWaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("StatusWaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for Wi-Fi ähnelt.
        /// </summary>
        public static string StatusWaitingForWiFi {
            get {
                return ResourceManager.GetString("StatusWaitingForWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CHOOSE TIME ähnelt.
        /// </summary>
        public static string TimePickerTitle {
            get {
                return ResourceManager.GetString("TimePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} hours ago ähnelt.
        /// </summary>
        public static string XHoursAgo_2To4 {
            get {
                return ResourceManager.GetString("XHoursAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} hours ago ähnelt.
        /// </summary>
        public static string XHoursAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XHoursAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} hours ago ähnelt.
        /// </summary>
        public static string XHoursAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XHoursAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} hours ago ähnelt.
        /// </summary>
        public static string XHoursAgo_Other {
            get {
                return ResourceManager.GetString("XHoursAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} minutes ago ähnelt.
        /// </summary>
        public static string XMinutesAgo_2To4 {
            get {
                return ResourceManager.GetString("XMinutesAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} minutes ago ähnelt.
        /// </summary>
        public static string XMinutesAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XMinutesAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} minutes ago ähnelt.
        /// </summary>
        public static string XMinutesAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XMinutesAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} minutes ago ähnelt.
        /// </summary>
        public static string XMinutesAgo_Other {
            get {
                return ResourceManager.GetString("XMinutesAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} months ago ähnelt.
        /// </summary>
        public static string XMonthsAgo_2To4 {
            get {
                return ResourceManager.GetString("XMonthsAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} months ago ähnelt.
        /// </summary>
        public static string XMonthsAgo_5To12 {
            get {
                return ResourceManager.GetString("XMonthsAgo_5To12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} seconds ago ähnelt.
        /// </summary>
        public static string XSecondsAgo_2To4 {
            get {
                return ResourceManager.GetString("XSecondsAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} seconds ago ähnelt.
        /// </summary>
        public static string XSecondsAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XSecondsAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} seconds ago ähnelt.
        /// </summary>
        public static string XSecondsAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XSecondsAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} seconds ago ähnelt.
        /// </summary>
        public static string XSecondsAgo_Other {
            get {
                return ResourceManager.GetString("XSecondsAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} weeks ago ähnelt.
        /// </summary>
        public static string XWeeksAgo_2To4 {
            get {
                return ResourceManager.GetString("XWeeksAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yes ähnelt.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
