//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34003
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Phone.Controls.Updated.LocalizedResources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Phone.Controls.Updated.LocalizedResources.ControlResources", typeof(ControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a about a minute ago.
        /// </summary>
        public static string AboutAMinuteAgo {
            get {
                return ResourceManager.GetString("AboutAMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a about a month ago.
        /// </summary>
        public static string AboutAMonthAgo {
            get {
                return ResourceManager.GetString("AboutAMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a about an hour ago.
        /// </summary>
        public static string AboutAnHourAgo {
            get {
                return ResourceManager.GetString("AboutAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a about a week ago.
        /// </summary>
        public static string AboutAWeekAgo {
            get {
                return ResourceManager.GetString("AboutAWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ALARM REPEATS ON.
        /// </summary>
        public static string AlarmRepeatsOn {
            get {
                return ResourceManager.GetString("AlarmRepeatsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a bytes.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CHOOSE DATE.
        /// </summary>
        public static string DatePickerTitle {
            get {
                return ResourceManager.GetString("DatePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cancel.
        /// </summary>
        public static string DateTimePickerCancelText {
            get {
                return ResourceManager.GetString("DateTimePickerCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a done.
        /// </summary>
        public static string DateTimePickerDoneText {
            get {
                return ResourceManager.GetString("DateTimePickerDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GB.
        /// </summary>
        public static string Gigabyte {
            get {
                return ResourceManager.GetString("Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a KB.
        /// </summary>
        public static string Kilobyte {
            get {
                return ResourceManager.GetString("Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a last Friday.
        /// </summary>
        public static string last_Friday {
            get {
                return ResourceManager.GetString("last Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a last Monday.
        /// </summary>
        public static string last_Monday {
            get {
                return ResourceManager.GetString("last Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a last Saturday.
        /// </summary>
        public static string last_Saturday {
            get {
                return ResourceManager.GetString("last Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a last Sunday.
        /// </summary>
        public static string last_Sunday {
            get {
                return ResourceManager.GetString("last Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a last Thursday.
        /// </summary>
        public static string last_Thursday {
            get {
                return ResourceManager.GetString("last Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a last Tuesday.
        /// </summary>
        public static string last_Tuesday {
            get {
                return ResourceManager.GetString("last Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a last Wednesday.
        /// </summary>
        public static string last_Wednesday {
            get {
                return ResourceManager.GetString("last Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MB.
        /// </summary>
        public static string Megabyte {
            get {
                return ResourceManager.GetString("Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a on Friday.
        /// </summary>
        public static string on_Friday {
            get {
                return ResourceManager.GetString("on Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a on Monday.
        /// </summary>
        public static string on_Monday {
            get {
                return ResourceManager.GetString("on Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a on Saturday.
        /// </summary>
        public static string on_Saturday {
            get {
                return ResourceManager.GetString("on Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a on Sunday.
        /// </summary>
        public static string on_Sunday {
            get {
                return ResourceManager.GetString("on Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a on Thursday.
        /// </summary>
        public static string on_Thursday {
            get {
                return ResourceManager.GetString("on Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a on Tuesday.
        /// </summary>
        public static string on_Tuesday {
            get {
                return ResourceManager.GetString("on Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a on Wednesday.
        /// </summary>
        public static string on_Wednesday {
            get {
                return ResourceManager.GetString("on Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a over a year ago.
        /// </summary>
        public static string OverAYearAgo {
            get {
                return ResourceManager.GetString("OverAYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} of {1}.
        /// </summary>
        public static string PartOfWhole {
            get {
                return ResourceManager.GetString("PartOfWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a every day.
        /// </summary>
        public static string RepeatsEveryDay {
            get {
                return ResourceManager.GetString("RepeatsEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a only once.
        /// </summary>
        public static string RepeatsOnlyOnce {
            get {
                return ResourceManager.GetString("RepeatsOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a weekdays.
        /// </summary>
        public static string RepeatsOnWeekdays {
            get {
                return ResourceManager.GetString("RepeatsOnWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a weekends.
        /// </summary>
        public static string RepeatsOnWeekends {
            get {
                return ResourceManager.GetString("RepeatsOnWeekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Canceled.
        /// </summary>
        public static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a complete.
        /// </summary>
        public static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Downloading....
        /// </summary>
        public static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        public static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a paused.
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pending.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a unknown.
        /// </summary>
        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uploading....
        /// </summary>
        public static string StatusUploading {
            get {
                return ResourceManager.GetString("StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Waiting....
        /// </summary>
        public static string StatusWaiting {
            get {
                return ResourceManager.GetString("StatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Waiting....
        /// </summary>
        public static string StatusWaitingForExternalPower {
            get {
                return ResourceManager.GetString("StatusWaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Low battery.
        /// </summary>
        public static string StatusWaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("StatusWaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Waiting for connection.
        /// </summary>
        public static string StatusWaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("StatusWaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Waiting for Wi-Fi.
        /// </summary>
        public static string StatusWaitingForWiFi {
            get {
                return ResourceManager.GetString("StatusWaitingForWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CHOOSE TIME.
        /// </summary>
        public static string TimePickerTitle {
            get {
                return ResourceManager.GetString("TimePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} hours ago.
        /// </summary>
        public static string XHoursAgo_2To4 {
            get {
                return ResourceManager.GetString("XHoursAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} hours ago.
        /// </summary>
        public static string XHoursAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XHoursAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} hours ago.
        /// </summary>
        public static string XHoursAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XHoursAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} hours ago.
        /// </summary>
        public static string XHoursAgo_Other {
            get {
                return ResourceManager.GetString("XHoursAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo_2To4 {
            get {
                return ResourceManager.GetString("XMinutesAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XMinutesAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XMinutesAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo_Other {
            get {
                return ResourceManager.GetString("XMinutesAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} months ago.
        /// </summary>
        public static string XMonthsAgo_2To4 {
            get {
                return ResourceManager.GetString("XMonthsAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} months ago.
        /// </summary>
        public static string XMonthsAgo_5To12 {
            get {
                return ResourceManager.GetString("XMonthsAgo_5To12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo_2To4 {
            get {
                return ResourceManager.GetString("XSecondsAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XSecondsAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XSecondsAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo_Other {
            get {
                return ResourceManager.GetString("XSecondsAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} weeks ago.
        /// </summary>
        public static string XWeeksAgo_2To4 {
            get {
                return ResourceManager.GetString("XWeeksAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
