//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparklrWP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparklrWP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sparklr*.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your user name and password used on Sparklr. If you don&apos;t have an account yet, sign up! It&apos;s free!.
        /// </summary>
        public static string FirstRunBasics1 {
            get {
                return ResourceManager.GetString("FirstRunBasics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The power of the pivot! Slide over on the main page for more things to do! It&apos;s like having the power of Sparklr in your hands!.
        /// </summary>
        public static string FirstRunBasics2 {
            get {
                return ResourceManager.GetString("FirstRunBasics2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there :).
        /// </summary>
        public static string FirstRunHelloThere {
            get {
                return ResourceManager.GetString("FirstRunHelloThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets get started!.
        /// </summary>
        public static string FirstRunLetsGetStarted {
            get {
                return ResourceManager.GetString("FirstRunLetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string FirstRunLogin {
            get {
                return ResourceManager.GetString("FirstRunLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like it&apos;s the first time you&apos;ve used this app! We will take you through a small intro to show you around the app!.
        /// </summary>
        public static string FirstRunMsgBoxContent {
            get {
                return ResourceManager.GetString("FirstRunMsgBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have we met before?.
        /// </summary>
        public static string FirstRunMsgBoxTitle {
            get {
                return ResourceManager.GetString("FirstRunMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK!.
        /// </summary>
        public static string FirstRunOK {
            get {
                return ResourceManager.GetString("FirstRunOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other stuff.
        /// </summary>
        public static string FirstRunOtherStuff {
            get {
                return ResourceManager.GetString("FirstRunOtherStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On most pages you will see a bar with an icon! Those are passage ways to other parts in the app!.
        /// </summary>
        public static string FirstRunOtherStuff1 {
            get {
                return ResourceManager.GetString("FirstRunOtherStuff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide over.
        /// </summary>
        public static string FirstRunSlideOver {
            get {
                return ResourceManager.GetString("FirstRunSlideOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the basics.
        /// </summary>
        public static string FirstRunTheBasics {
            get {
                return ResourceManager.GetString("FirstRunTheBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dashboard:.
        /// </summary>
        public static string FirstRunTheDash {
            get {
                return ResourceManager.GetString("FirstRunTheDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login page:.
        /// </summary>
        public static string FirstRunTheLoginPage {
            get {
                return ResourceManager.GetString("FirstRunTheLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The three dots!.
        /// </summary>
        public static string FirstRunThreeDots {
            get {
                return ResourceManager.GetString("FirstRunThreeDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you waiting for?! Try it yourself!.
        /// </summary>
        public static string FirstRunWhatAreYouWaitingFor {
            get {
                return ResourceManager.GetString("FirstRunWhatAreYouWaitingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LoginAboutButton {
            get {
                return ResourceManager.GetString("LoginAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Windows Phone.
        /// </summary>
        public static string LoginForWP {
            get {
                return ResourceManager.GetString("LoginForWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLoginButton {
            get {
                return ResourceManager.GetString("LoginLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in.
        /// </summary>
        public static string LoginPleaseLogin {
            get {
                return ResourceManager.GetString("LoginPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string LoginSignUpButton {
            get {
                return ResourceManager.GetString("LoginSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sparklr*.
        /// </summary>
        public static string LoginSparklrLogo {
            get {
                return ResourceManager.GetString("LoginSparklrLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORK IN PROGRESS.
        /// </summary>
        public static string LoginWIP {
            get {
                return ResourceManager.GetString("LoginWIP", resourceCulture);
            }
        }
    }
}
