//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18213
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparklrWP.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparklrWP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Looks like you had a crash the last time you used the app. Would you like to help us fix the bug and send a quick bug report? ähnelt.
        /// </summary>
        public static string AppCrashReportText {
            get {
                return ResourceManager.GetString("AppCrashReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something went wrong... ähnelt.
        /// </summary>
        public static string AppCrashReportTitle {
            get {
                return ResourceManager.GetString("AppCrashReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sparklr* ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have {0} notifications. ähnelt.
        /// </summary>
        public static string AppNotificationText {
            get {
                return ResourceManager.GetString("AppNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your user name and password used on Sparklr. If you don&apos;t have an account yet, sign up! It&apos;s free! ähnelt.
        /// </summary>
        public static string FirstRunBasics1 {
            get {
                return ResourceManager.GetString("FirstRunBasics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The power of the pivot! Slide over on the main page for more things to do! It&apos;s like having the power of Sparklr in your hands! ähnelt.
        /// </summary>
        public static string FirstRunBasics2 {
            get {
                return ResourceManager.GetString("FirstRunBasics2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hello there :) ähnelt.
        /// </summary>
        public static string FirstRunHelloThere {
            get {
                return ResourceManager.GetString("FirstRunHelloThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lets get started! ähnelt.
        /// </summary>
        public static string FirstRunLetsGetStarted {
            get {
                return ResourceManager.GetString("FirstRunLetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login: ähnelt.
        /// </summary>
        public static string FirstRunLogin {
            get {
                return ResourceManager.GetString("FirstRunLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Looks like it&apos;s the first time you&apos;ve used this app! We will take you through a small intro to show you around the app! ähnelt.
        /// </summary>
        public static string FirstRunMsgBoxContent {
            get {
                return ResourceManager.GetString("FirstRunMsgBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have we met before? ähnelt.
        /// </summary>
        public static string FirstRunMsgBoxTitle {
            get {
                return ResourceManager.GetString("FirstRunMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK! ähnelt.
        /// </summary>
        public static string FirstRunOK {
            get {
                return ResourceManager.GetString("FirstRunOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die other stuff ähnelt.
        /// </summary>
        public static string FirstRunOtherStuff {
            get {
                return ResourceManager.GetString("FirstRunOtherStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On most pages you will see a bar with an icon! Those are passage ways to other parts in the app! ähnelt.
        /// </summary>
        public static string FirstRunOtherStuff1 {
            get {
                return ResourceManager.GetString("FirstRunOtherStuff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slide over ähnelt.
        /// </summary>
        public static string FirstRunSlideOver {
            get {
                return ResourceManager.GetString("FirstRunSlideOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the basics ähnelt.
        /// </summary>
        public static string FirstRunTheBasics {
            get {
                return ResourceManager.GetString("FirstRunTheBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The dashboard: ähnelt.
        /// </summary>
        public static string FirstRunTheDash {
            get {
                return ResourceManager.GetString("FirstRunTheDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The login page: ähnelt.
        /// </summary>
        public static string FirstRunTheLoginPage {
            get {
                return ResourceManager.GetString("FirstRunTheLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The three dots! ähnelt.
        /// </summary>
        public static string FirstRunThreeDots {
            get {
                return ResourceManager.GetString("FirstRunThreeDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What are you waiting for?! Try it yourself! ähnelt.
        /// </summary>
        public static string FirstRunWhatAreYouWaitingFor {
            get {
                return ResourceManager.GetString("FirstRunWhatAreYouWaitingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string LoginAboutButton {
            get {
                return ResourceManager.GetString("LoginAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sign up page will open in Internet Explorer, is that OK? ähnelt.
        /// </summary>
        public static string LoginBrowserOpenQuestionContent {
            get {
                return ResourceManager.GetString("LoginBrowserOpenQuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string LoginBrowserOpenQuestionTitle {
            get {
                return ResourceManager.GetString("LoginBrowserOpenQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to exit the app? Unsaved changes will be lost. ähnelt.
        /// </summary>
        public static string LoginExitConfirmationContent {
            get {
                return ResourceManager.GetString("LoginExitConfirmationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirmation ähnelt.
        /// </summary>
        public static string LoginExitConfirmationTitle {
            get {
                return ResourceManager.GetString("LoginExitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for Windows Phone ähnelt.
        /// </summary>
        public static string LoginForWP {
            get {
                return ResourceManager.GetString("LoginForWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string LoginLoginButton {
            get {
                return ResourceManager.GetString("LoginLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please log in ähnelt.
        /// </summary>
        public static string LoginPleaseLogin {
            get {
                return ResourceManager.GetString("LoginPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember Me ähnelt.
        /// </summary>
        public static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign up ähnelt.
        /// </summary>
        public static string LoginSignUpButton {
            get {
                return ResourceManager.GetString("LoginSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sparklr* ähnelt.
        /// </summary>
        public static string LoginSparklrLogo {
            get {
                return ResourceManager.GetString("LoginSparklrLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something horrible happend, try again later! ähnelt.
        /// </summary>
        public static string LoginUnknownLoginErrorMsgBoxContent {
            get {
                return ResourceManager.GetString("LoginUnknownLoginErrorMsgBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry! ähnelt.
        /// </summary>
        public static string LoginUnknownLoginErrorMsgBoxTitle {
            get {
                return ResourceManager.GetString("LoginUnknownLoginErrorMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WORK IN PROGRESS ähnelt.
        /// </summary>
        public static string LoginWIP {
            get {
                return ResourceManager.GetString("LoginWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong username and/or password ähnelt.
        /// </summary>
        public static string LoginWrongUserPass {
            get {
                return ResourceManager.GetString("LoginWrongUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about... ähnelt.
        /// </summary>
        public static string MainAboutButton {
            get {
                return ResourceManager.GetString("MainAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die friends ähnelt.
        /// </summary>
        public static string MainFriendsHeader {
            get {
                return ResourceManager.GetString("MainFriendsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die networks ähnelt.
        /// </summary>
        public static string MainNetworksHeader {
            get {
                return ResourceManager.GetString("MainNetworksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new post ähnelt.
        /// </summary>
        public static string MainNewPostButton {
            get {
                return ResourceManager.GetString("MainNewPostButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die notifications ähnelt.
        /// </summary>
        public static string MainNotifications {
            get {
                return ResourceManager.GetString("MainNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die profile ähnelt.
        /// </summary>
        public static string MainProfileHeader {
            get {
                return ResourceManager.GetString("MainProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die search ähnelt.
        /// </summary>
        public static string MainSearchButton {
            get {
                return ResourceManager.GetString("MainSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die settings ähnelt.
        /// </summary>
        public static string MainSettingsButton {
            get {
                return ResourceManager.GetString("MainSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit network... ähnelt.
        /// </summary>
        public static string MainVisitNetworkHint {
            get {
                return ResourceManager.GetString("MainVisitNetworkHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die world ähnelt.
        /// </summary>
        public static string MainWorldHeader {
            get {
                return ResourceManager.GetString("MainWorldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press the &quot;Picture&quot; button down below to attach a picture ähnelt.
        /// </summary>
        public static string NewPostAttachPictureHint {
            get {
                return ResourceManager.GetString("NewPostAttachPictureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something horrible happend!
        ///We couldn&apos;t post your message try again later! ähnelt.
        /// </summary>
        public static string NewPostCouldNotPostMsg {
            get {
                return ResourceManager.GetString("NewPostCouldNotPostMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something horrible happend!
        ///We couldn&apos;t post your message  and photo try again later! ähnelt.
        /// </summary>
        public static string NewPostCouldNotPostMsgPic {
            get {
                return ResourceManager.GetString("NewPostCouldNotPostMsgPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry! ähnelt.
        /// </summary>
        public static string NewPostCouldNotPostMsgTitle {
            get {
                return ResourceManager.GetString("NewPostCouldNotPostMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need to say something! You can&apos;t post an empty message! ähnelt.
        /// </summary>
        public static string NewPostEmptyMsgWarning {
            get {
                return ResourceManager.GetString("NewPostEmptyMsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is an image editor! ähnelt.
        /// </summary>
        public static string NewPostImageEditorHint {
            get {
                return ResourceManager.GetString("NewPostImageEditorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network: ähnelt.
        /// </summary>
        public static string NewPostNetworkCaption {
            get {
                return ResourceManager.GetString("NewPostNetworkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new post ähnelt.
        /// </summary>
        public static string NewPostNewPostButton {
            get {
                return ResourceManager.GetString("NewPostNewPostButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die picture ähnelt.
        /// </summary>
        public static string NewPostPictureButton {
            get {
                return ResourceManager.GetString("NewPostPictureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Posted! :) ähnelt.
        /// </summary>
        public static string NewPostPostedMsg {
            get {
                return ResourceManager.GetString("NewPostPostedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove the attached image? ähnelt.
        /// </summary>
        public static string NewPostRemoveImageText {
            get {
                return ResourceManager.GetString("NewPostRemoveImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string NewPostRemoveImageTitle {
            get {
                return ResourceManager.GetString("NewPostRemoveImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your status has been posted! ähnelt.
        /// </summary>
        public static string NewPostSuccessText {
            get {
                return ResourceManager.GetString("NewPostSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yay! ähnelt.
        /// </summary>
        public static string NewPostSuccessTitle {
            get {
                return ResourceManager.GetString("NewPostSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Post ähnelt.
        /// </summary>
        public static string NewPostTitle {
            get {
                return ResourceManager.GetString("NewPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin ähnelt.
        /// </summary>
        public static string PinToStartCaption {
            get {
                return ResourceManager.GetString("PinToStartCaption", resourceCulture);
            }
        }
    }
}
