//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34011
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparklrForWindowsPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparklrForWindowsPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Looks like you had a crash the last time you used the app. Would you like to help us fix the bug and send a quick bug report?.
        /// </summary>
        public static string AppCrashReportText {
            get {
                return ResourceManager.GetString("AppCrashReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Something went wrong....
        /// </summary>
        public static string AppCrashReportTitle {
            get {
                return ResourceManager.GetString("AppCrashReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a sparklr*.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You have {0} notifications..
        /// </summary>
        public static string AppNotificationText {
            get {
                return ResourceManager.GetString("AppNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updates tiles and notifications..
        /// </summary>
        public static string BackgroundAgentDescription {
            get {
                return ResourceManager.GetString("BackgroundAgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sparklr*.
        /// </summary>
        public static string BackgroundAgentName {
            get {
                return ResourceManager.GetString("BackgroundAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter your user name and password used on Sparklr. If you don&apos;t have an account yet, sign up! It&apos;s free!.
        /// </summary>
        public static string FirstRunBasics1 {
            get {
                return ResourceManager.GetString("FirstRunBasics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The power of the pivot! Slide over on the main page for more things to do! It&apos;s like having the power of Sparklr in your hands!.
        /// </summary>
        public static string FirstRunBasics2 {
            get {
                return ResourceManager.GetString("FirstRunBasics2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hello there :).
        /// </summary>
        public static string FirstRunHelloThere {
            get {
                return ResourceManager.GetString("FirstRunHelloThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lets get started!.
        /// </summary>
        public static string FirstRunLetsGetStarted {
            get {
                return ResourceManager.GetString("FirstRunLetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login:.
        /// </summary>
        public static string FirstRunLogin {
            get {
                return ResourceManager.GetString("FirstRunLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Looks like it&apos;s the first time you&apos;ve used this app! We will take you through a small intro to show you around the app!.
        /// </summary>
        public static string FirstRunMsgBoxContent {
            get {
                return ResourceManager.GetString("FirstRunMsgBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Have we met before?.
        /// </summary>
        public static string FirstRunMsgBoxTitle {
            get {
                return ResourceManager.GetString("FirstRunMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK!.
        /// </summary>
        public static string FirstRunOK {
            get {
                return ResourceManager.GetString("FirstRunOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a other stuff.
        /// </summary>
        public static string FirstRunOtherStuff {
            get {
                return ResourceManager.GetString("FirstRunOtherStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a On most pages you will see a bar with an icon! Those are passage ways to other parts in the app!.
        /// </summary>
        public static string FirstRunOtherStuff1 {
            get {
                return ResourceManager.GetString("FirstRunOtherStuff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Slide over.
        /// </summary>
        public static string FirstRunSlideOver {
            get {
                return ResourceManager.GetString("FirstRunSlideOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a the basics.
        /// </summary>
        public static string FirstRunTheBasics {
            get {
                return ResourceManager.GetString("FirstRunTheBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The dashboard:.
        /// </summary>
        public static string FirstRunTheDash {
            get {
                return ResourceManager.GetString("FirstRunTheDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The login page:.
        /// </summary>
        public static string FirstRunTheLoginPage {
            get {
                return ResourceManager.GetString("FirstRunTheLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The three dots!.
        /// </summary>
        public static string FirstRunThreeDots {
            get {
                return ResourceManager.GetString("FirstRunThreeDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a What are you waiting for?! Try it yourself!.
        /// </summary>
        public static string FirstRunWhatAreYouWaitingFor {
            get {
                return ResourceManager.GetString("FirstRunWhatAreYouWaitingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        public static string LoginAboutButton {
            get {
                return ResourceManager.GetString("LoginAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The sign up page will open in Internet Explorer, is that OK?.
        /// </summary>
        public static string LoginBrowserOpenQuestionContent {
            get {
                return ResourceManager.GetString("LoginBrowserOpenQuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Question.
        /// </summary>
        public static string LoginBrowserOpenQuestionTitle {
            get {
                return ResourceManager.GetString("LoginBrowserOpenQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to exit the app? Unsaved changes will be lost..
        /// </summary>
        public static string LoginExitConfirmationContent {
            get {
                return ResourceManager.GetString("LoginExitConfirmationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirmation.
        /// </summary>
        public static string LoginExitConfirmationTitle {
            get {
                return ResourceManager.GetString("LoginExitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a for Windows Phone.
        /// </summary>
        public static string LoginForWP {
            get {
                return ResourceManager.GetString("LoginForWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        public static string LoginLoginButton {
            get {
                return ResourceManager.GetString("LoginLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please log in.
        /// </summary>
        public static string LoginPleaseLogin {
            get {
                return ResourceManager.GetString("LoginPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remember Me.
        /// </summary>
        public static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign up.
        /// </summary>
        public static string LoginSignUpButton {
            get {
                return ResourceManager.GetString("LoginSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a sparklr*.
        /// </summary>
        public static string LoginSparklrLogo {
            get {
                return ResourceManager.GetString("LoginSparklrLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Something horrible happend, try again later!.
        /// </summary>
        public static string LoginUnknownLoginErrorMsgBoxContent {
            get {
                return ResourceManager.GetString("LoginUnknownLoginErrorMsgBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorry!.
        /// </summary>
        public static string LoginUnknownLoginErrorMsgBoxTitle {
            get {
                return ResourceManager.GetString("LoginUnknownLoginErrorMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a WORK IN PROGRESS.
        /// </summary>
        public static string LoginWIP {
            get {
                return ResourceManager.GetString("LoginWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wrong username and/or password.
        /// </summary>
        public static string LoginWrongUserPass {
            get {
                return ResourceManager.GetString("LoginWrongUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a logout....
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a about....
        /// </summary>
        public static string MainAboutButton {
            get {
                return ResourceManager.GetString("MainAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a friends.
        /// </summary>
        public static string MainFriendsHeader {
            get {
                return ResourceManager.GetString("MainFriendsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a networks.
        /// </summary>
        public static string MainNetworksHeader {
            get {
                return ResourceManager.GetString("MainNetworksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a new post.
        /// </summary>
        public static string MainNewPostButton {
            get {
                return ResourceManager.GetString("MainNewPostButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a notifications.
        /// </summary>
        public static string MainNotifications {
            get {
                return ResourceManager.GetString("MainNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a profile.
        /// </summary>
        public static string MainProfileHeader {
            get {
                return ResourceManager.GetString("MainProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a search.
        /// </summary>
        public static string MainSearchButton {
            get {
                return ResourceManager.GetString("MainSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a settings.
        /// </summary>
        public static string MainSettingsButton {
            get {
                return ResourceManager.GetString("MainSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visit network....
        /// </summary>
        public static string MainVisitNetworkHint {
            get {
                return ResourceManager.GetString("MainVisitNetworkHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a world.
        /// </summary>
        public static string MainWorldHeader {
            get {
                return ResourceManager.GetString("MainWorldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Press the &quot;Picture&quot; button down below to attach a picture.
        /// </summary>
        public static string NewPostAttachPictureHint {
            get {
                return ResourceManager.GetString("NewPostAttachPictureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Something horrible happend!
        ///We couldn&apos;t post your message try again later!.
        /// </summary>
        public static string NewPostCouldNotPostMsg {
            get {
                return ResourceManager.GetString("NewPostCouldNotPostMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Something horrible happend!
        ///We couldn&apos;t post your message  and photo try again later!.
        /// </summary>
        public static string NewPostCouldNotPostMsgPic {
            get {
                return ResourceManager.GetString("NewPostCouldNotPostMsgPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorry!.
        /// </summary>
        public static string NewPostCouldNotPostMsgTitle {
            get {
                return ResourceManager.GetString("NewPostCouldNotPostMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You need to say something! You can&apos;t post an empty message!.
        /// </summary>
        public static string NewPostEmptyMsgWarning {
            get {
                return ResourceManager.GetString("NewPostEmptyMsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There is an image editor!.
        /// </summary>
        public static string NewPostImageEditorHint {
            get {
                return ResourceManager.GetString("NewPostImageEditorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Network:.
        /// </summary>
        public static string NewPostNetworkCaption {
            get {
                return ResourceManager.GetString("NewPostNetworkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a new post.
        /// </summary>
        public static string NewPostNewPostButton {
            get {
                return ResourceManager.GetString("NewPostNewPostButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a picture.
        /// </summary>
        public static string NewPostPictureButton {
            get {
                return ResourceManager.GetString("NewPostPictureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Posted! :).
        /// </summary>
        public static string NewPostPostedMsg {
            get {
                return ResourceManager.GetString("NewPostPostedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to remove the attached image?.
        /// </summary>
        public static string NewPostRemoveImageText {
            get {
                return ResourceManager.GetString("NewPostRemoveImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Question.
        /// </summary>
        public static string NewPostRemoveImageTitle {
            get {
                return ResourceManager.GetString("NewPostRemoveImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your status has been posted!.
        /// </summary>
        public static string NewPostSuccessText {
            get {
                return ResourceManager.GetString("NewPostSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yay!.
        /// </summary>
        public static string NewPostSuccessTitle {
            get {
                return ResourceManager.GetString("NewPostSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Post.
        /// </summary>
        public static string NewPostTitle {
            get {
                return ResourceManager.GetString("NewPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pin.
        /// </summary>
        public static string PinToStartCaption {
            get {
                return ResourceManager.GetString("PinToStartCaption", resourceCulture);
            }
        }
    }
}
